/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Totaldo
 */
public class Alt extends javax.swing.JFrame {

    /**
     * Creates new form Alt
     */
    public Alt() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_alt = new javax.swing.JTable();
        aceptar_alt = new javax.swing.JButton();
        cerrar_alt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(735, 0, 0, 0));

        tabla_alt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_alt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_altMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_alt);

        aceptar_alt.setText("Agregar");
        aceptar_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_altActionPerformed(evt);
            }
        });

        cerrar_alt.setText("Cerrar");
        cerrar_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar_altActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar_alt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrar_alt)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar_alt)
                    .addComponent(cerrar_alt))
                .addGap(0, 113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrar_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar_altActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cerrar_altActionPerformed

    private void aceptar_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_altActionPerformed
try{
        DefaultTableModel temp = (DefaultTableModel) Busqueda_productos.tabla.getModel();
    Object nuevo[]= {tabla_alt.getValueAt(tabla_alt.getSelectedRow(), 1),tabla_alt.getValueAt(tabla_alt.getSelectedRow(), 0),tabla_alt.getValueAt(tabla_alt.getSelectedRow(), 2)};
    temp.addRow(nuevo); 
}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al agregar datos");
}
    }//GEN-LAST:event_aceptar_altActionPerformed

    private void tabla_altMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_altMouseClicked
if(evt.getClickCount()==2){
try{
        DefaultTableModel temp = (DefaultTableModel) Busqueda_productos.tabla.getModel();
    Object nuevo[]= {tabla_alt.getValueAt(tabla_alt.getSelectedRow(), 1),tabla_alt.getValueAt(tabla_alt.getSelectedRow(), 0),tabla_alt.getValueAt(tabla_alt.getSelectedRow(), 2)};
    temp.addRow(nuevo); 
}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al agregar datos");
}
}        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_altMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alt().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar_alt;
    private javax.swing.JButton cerrar_alt;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla_alt;
    // End of variables declaration//GEN-END:variables
}
