/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Totaldo
 */
public class Busqueda_productos extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda_productos
     */
    public Busqueda_productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        if(evt.getClickCount()>=2){

            DefaultTableModel temp = (DefaultTableModel) p_venta.tabla2.getModel();
            Object nuevo[]= {tabla.getValueAt(tabla.getSelectedRow(), 1),tabla.getValueAt(tabla.getSelectedRow(), 0),tabla.getValueAt(tabla.getSelectedRow(), 2),tabla.getValueAt(tabla.getSelectedRow(), 3),tabla.getValueAt(tabla.getSelectedRow(), 2)};
            temp.addRow(nuevo);
            this.dispose();
            p_venta.tabla2.requestFocus();
p_venta.tabla2.changeSelection(p_venta.tabla2.getRowCount()-1, 0, false,false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_DOWN){
tabla.requestFocus();
tabla.changeSelection(0, 0, false, false);
}
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
//       if(evt.getKeyCode()==KeyEvent.VK_DOWN){
//tabla.requestFocus();
//tabla.changeSelection(0, 0, false, false);
//} // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
 
  
       
        Connection miConexion;
        miConexion=Conexion.GetConnection();
      
        if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
        try{
Statement st = miConexion.createStatement();
ResultSet r=st.executeQuery("SELECT * FROM producto WHERE PRO_NOMBRE LIKE '"+jTextField1.getText()+"%';");

while(r.next()) {
/*
Imprimo por consola el nombre y la nota de todos los alumnos ingresados a la base de datos
*/
    DefaultTableModel temp = (DefaultTableModel)tabla.getModel();
    Object nuevo[]= {r.getString("PRO_NOMBRE"),r.getString("PRO_CODIGO"),r.getString("PRO_PRECIO"),1,r.getString("PRO_PRECIO")};
    temp.addRow(nuevo);
    
//tabla.setValueAt(r.getString("PRO_NOMBRE"), 0, 0);
//tabla.setValueAt(r.getString("PRO_CODIGO"), 0, 1);
//tabla.setValueAt(r.getString("PRO_PRECIO"), 0, 2);
}


}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al extraer datos"+e.toString());
}            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
if(tabla.getSelectedRow()==0&&evt.getKeyCode()==KeyEvent.VK_UP){
jTextField1.requestFocus();
}  
if(evt.getKeyCode()==10)
{
 DefaultTableModel temp = (DefaultTableModel) p_venta.tabla2.getModel();
            Object nuevo[]= {tabla.getValueAt(tabla.getSelectedRow(), 1),tabla.getValueAt(tabla.getSelectedRow(), 0),tabla.getValueAt(tabla.getSelectedRow(), 2),tabla.getValueAt(tabla.getSelectedRow(), 3),tabla.getValueAt(tabla.getSelectedRow(), 2)};
            temp.addRow(nuevo);
            this.dispose();
            p_venta.tabla2.requestFocus();
p_venta.tabla2.changeSelection(p_venta.tabla2.getRowCount()-1, 0, false,false);
}// TODO add your handling code here:
    }//GEN-LAST:event_tablaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda_productos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
