/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Totaldo
 */
public class Home extends javax.swing.JFrame {
static Image icon;
p_venta punto;
Caja caja;
static String perm;
    /**
     * Creates new form Home
     * @param permiso
     */
    public Home(String permiso) {
        perm=permiso;
        icon=Toolkit.getDefaultToolkit().createImage("src/empresa/pv_new.jpg");

        initComponents();
                pv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\pv.jpg"))); 
        caja_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\caja.jpg")));
        admin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\admin.png")));
        nc_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\nc.jpg")));
        nd_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\nc.jpg")));
        if(perm.equals("vendedor")){
            caja_button.setEnabled(false);
        admin_button.setEnabled(false);
        nc_button.setEnabled(false);
        nd_button.setEnabled(false);
        }
        if(perm.equals("cajero")){
            pv_button.setEnabled(false);
        admin_button.setEnabled(false);
        }
        
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja_button = new javax.swing.JButton();
        pv_button = new javax.swing.JButton();
        admin_button = new javax.swing.JButton();
        nc_button = new javax.swing.JButton();
        nd_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        caja_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        caja_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caja_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                caja_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caja_buttonMouseExited(evt);
            }
        });
        caja_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_buttonActionPerformed(evt);
            }
        });

        pv_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pv_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pv_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pv_buttonMouseExited(evt);
            }
        });
        pv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pv_buttonActionPerformed(evt);
            }
        });

        admin_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admin_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admin_buttonMouseExited(evt);
            }
        });
        admin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_buttonActionPerformed(evt);
            }
        });

        nc_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nc_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nc_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nc_buttonMouseExited(evt);
            }
        });

        nd_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nd_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nd_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nd_buttonMouseExited(evt);
            }
        });

        jLabel1.setText("Caja");

        jLabel2.setText("Punto de Venta");

        jLabel3.setText("Administración");

        jLabel4.setText("Nota de credito");

        jLabel5.setText("Nota de debito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel2)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(nc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(nd_button))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(caja_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pv_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(admin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pv_button, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                    .addComponent(admin_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caja_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nd_button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(nc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pv_buttonMouseEntered
pv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\pv_new.jpg")));  
// TODO add your handling code here:
    }//GEN-LAST:event_pv_buttonMouseEntered

    private void pv_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pv_buttonMouseExited
      pv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\pv.jpg")));  // TODO add your handling code here:
    }//GEN-LAST:event_pv_buttonMouseExited

    private void caja_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caja_buttonMouseEntered
caja_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\caja_new.jpg")));        // TODO add your handling code here:
    }//GEN-LAST:event_caja_buttonMouseEntered

    private void caja_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caja_buttonMouseExited
      caja_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\caja.jpg")));  // TODO add your handling code here:
    }//GEN-LAST:event_caja_buttonMouseExited

    private void caja_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caja_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_buttonMouseClicked

    private void pv_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pv_buttonMouseClicked
     
      // TODO add your handling code here:
    }//GEN-LAST:event_pv_buttonMouseClicked

    private void admin_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_buttonMouseEntered
      admin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\admin_new.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_admin_buttonMouseEntered

    private void admin_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_buttonMouseExited
      admin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\admin.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_admin_buttonMouseExited

    private void admin_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_buttonMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_admin_buttonMouseClicked

    private void admin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_buttonActionPerformed
        admin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\admin.png")));
       JOptionPane.showMessageDialog(this, "En construccion"); // TODO add your handling code here:
    }//GEN-LAST:event_admin_buttonActionPerformed

    private void caja_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_buttonActionPerformed
      caja_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\caja.jpg")));
     caja= new Caja(perm);
     caja.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_buttonActionPerformed

    private void pv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pv_buttonActionPerformed
        pv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\pv.jpg")));
      punto=new p_venta(perm);
      punto.setVisible(true);
    do{
      this.dispose();
    }while(punto.isActive());// TODO add your handling code here:
      
    }//GEN-LAST:event_pv_buttonActionPerformed

    private void nc_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc_buttonMouseEntered
       nc_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\nc_new.jpg"))); // TODO add your handling code here:
    }//GEN-LAST:event_nc_buttonMouseEntered

    private void nc_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc_buttonMouseExited
       nc_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\nc.jpg"))); // TODO add your handling code here:
    }//GEN-LAST:event_nc_buttonMouseExited

    private void nd_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nd_buttonMouseEntered
       nd_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\nc_new.jpg"))); // TODO add your handling code here:
    }//GEN-LAST:event_nd_buttonMouseEntered

    private void nd_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nd_buttonMouseExited
      nd_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("\\nc.jpg")));  // TODO add your handling code here:
    }//GEN-LAST:event_nd_buttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(perm).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_button;
    private javax.swing.JButton caja_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton nc_button;
    private javax.swing.JButton nd_button;
    private javax.swing.JButton pv_button;
    // End of variables declaration//GEN-END:variables
}
