/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Totaldo
 */
public class Login extends javax.swing.JFrame {
Home home;
    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        this.setSize(300, 250);
         this.setLocationRelativeTo(null);
         this.setTitle("LOGIN");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        Pass_tf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        login_button.setText("Aceptar");
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
        });

        Pass_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_tfActionPerformed(evt);
            }
        });
        Pass_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Pass_tfKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_button)
                    .addComponent(Usuario_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(Pass_tf))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Pass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(login_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseClicked
boolean log=false;
        Connection miConexion=Conexion.GetConnection();
        
            if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
       
        try{
Statement st1 = miConexion.createStatement();
ResultSet r1=st1.executeQuery("SELECT * FROM usuarios ;");

while (r1.next()&&log==false)
{
     
  if(r1.getString(2).equals(Usuario_tf.getText())&&String.valueOf(r1.getInt(3)).equals(Pass_tf.getText()) ){
  //JOptionPane.showMessageDialog(this, Pass_tf.getText());
  home=new Home(r1.getString(4));
 home.setVisible(true);
 this.dispose();
 log=true;
  
  }
  
}
if(log==false){JOptionPane.showMessageDialog(this, "Login Incorecto");}




}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al loguear"+e.toString());
}        // TODO add your handling code here:
    }//GEN-LAST:event_login_buttonMouseClicked

    private void Pass_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass_tfActionPerformed

    private void Pass_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pass_tfKeyPressed
if(evt.getKeyCode()==10){
boolean log=false;
        Connection miConexion=Conexion.GetConnection();
        
            if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
       
        try{
Statement st1 = miConexion.createStatement();
ResultSet r1=st1.executeQuery("SELECT * FROM usuarios ;");

while (r1.next()&&log==false)
{
     
  if(r1.getString(2).equals(Usuario_tf.getText())&&String.valueOf(r1.getInt(3)).equals(Pass_tf.getText()) ){
  //JOptionPane.showMessageDialog(this, Pass_tf.getText());
  home=new Home(r1.getString(4));
 home.setVisible(true);
 this.dispose();
 log=true;
  
  }
  
}
if(log==false){JOptionPane.showMessageDialog(this, "Login Incorecto");}




}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al loguear"+e.toString());
}  
}        // TODO add your handling code here:
    }//GEN-LAST:event_Pass_tfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pass_tf;
    private javax.swing.JTextField Usuario_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_button;
    // End of variables declaration//GEN-END:variables
}
