/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Totaldo
 */
public class p_venta extends javax.swing.JFrame  {

    /**
     * Creates new form p_venta
     * 
     */Alt alter;
     Home home;
    static String permiso;
    
        
     Busqueda_productos busqueda;
    public p_venta(String perm) {
        permiso=perm;
           setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        initComponents();
        
        Connection miConexion=Conexion.GetConnection();
        Connection miConexion2=Conexion.GetConnection();
            if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
       
        try{
Statement st1 = miConexion.createStatement();
ResultSet r1=st1.executeQuery("SELECT * FROM correlativo ;");
while (r1.next())
{
  n_atencion.setText(String.valueOf(r1.getInt(1)));
}




}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al extraer datos"+e.toString());
}
        if(miConexion2!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
        try{
        PreparedStatement ps =miConexion2.prepareStatement("UPDATE correlativo SET corr=corr+1"); 
        ps.executeUpdate();
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error al actualizar datos"+e.toString());
        }
         this.setLocationRelativeTo(null);
         this.setTitle("VENTAS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        documentos_bg = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        Alt_boton = new javax.swing.JButton();
        n_atencion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ven_cod = new javax.swing.JTextField();
        ven_nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        desc_tf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        total_tf = new javax.swing.JTextField();
        print_b = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Ubicacion", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla2.setColumnSelectionAllowed(true);
        tabla2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabla2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabla2FocusLost(evt);
            }
        });
        tabla2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tabla2InputMethodTextChanged(evt);
            }
        });
        tabla2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabla2PropertyChange(evt);
            }
        });
        tabla2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabla2KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabla2);
        tabla2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabla2.getColumnModel().getColumnCount() > 0) {
            tabla2.getColumnModel().getColumn(0).setHeaderValue("Codigo");
            tabla2.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            tabla2.getColumnModel().getColumn(2).setHeaderValue("Precio");
            tabla2.getColumnModel().getColumn(3).setHeaderValue("Cantidad");
            tabla2.getColumnModel().getColumn(4).setHeaderValue("Total");
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CÓDIGO PRODUCTO");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        Alt_boton.setText("Alternativa");
        Alt_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alt_botonActionPerformed(evt);
            }
        });

        n_atencion.setEditable(false);
        n_atencion.setBackground(new java.awt.Color(204, 204, 204));
        n_atencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_atencionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("N° ATENCION ");

        ven_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ven_codActionPerformed(evt);
            }
        });
        ven_cod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ven_codFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ven_codFocusLost(evt);
            }
        });
        ven_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ven_codKeyPressed(evt);
            }
        });

        ven_nom.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" VENDEDOR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Descuento");

        desc_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                desc_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                desc_tfFocusLost(evt);
            }
        });
        desc_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desc_tfKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        documentos_bg.add(jCheckBox3);
        jCheckBox3.setText("Guia");

        documentos_bg.add(jCheckBox4);
        jCheckBox4.setText("Boleta");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        documentos_bg.add(jCheckBox1);
        jCheckBox1.setText("Factura");

        documentos_bg.add(jCheckBox5);
        jCheckBox5.setText("Cotizacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox5))
                .addGap(41, 41, 41))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("TOTAL:");

        total_tf.setEditable(false);

        print_b.setText("Imprimir");
        print_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_bActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cod. Cliente");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nombre Cliente");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("R.U.T Cliente");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Direccion Cliente");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empresa/old_edit_find.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Agregar Cliente");

        jLabel11.setText("Foto Referencial");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empresa/clients (1).png"))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Descripción", "Ubicacion", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Alternativas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Casa Matriz", "Suc. Serviflex", "Suc. Retiro", "Bodega"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jTable1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Stock Disponibles");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Telefono Cliente");

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Toto, hay que cambiar el tipo de documento a\"CAJA\", recuerda como lo habiamos hecho, que aparesca cuando pones una opcion");

        jLabel16.setText("Lo otro es hacer que todas las ventanas se abran en grande");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(total_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(print_b, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(desc_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrar)
                            .addComponent(Alt_boton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n_atencion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(ven_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ven_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ven_nom)
                                    .addComponent(ven_cod)
                                    .addComponent(n_atencion))
                                .addGap(22, 22, 22))
                            .addComponent(jButton3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desc_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(borrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alt_boton))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(total_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(print_b)
                                    .addComponent(jLabel16)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
     if(evt.getKeyCode()==KeyEvent.VK_F5){
busqueda = new Busqueda_productos();
       
       busqueda.show();
}
     if(evt.getKeyCode()==10){
     Connection miConexion;
        miConexion=Conexion.GetConnection();
      
        if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
        
        try{
Statement st = miConexion.createStatement();
ResultSet r=st.executeQuery("SELECT * FROM producto WHERE PRO_CODIGO ="+jTextField1.getText()+";");

while(r.next()) {
/*
Imprimo por consola el nombre y la nota de todos los alumnos ingresados a la base de datos
*/
    DefaultTableModel temp = (DefaultTableModel)tabla2.getModel();
    int total=r.getInt("PRO_Precio");
    Object nuevo[]= {r.getString("PRO_CODIGO"),r.getString("PRO_NOMBRE"),r.getString("PRO_PRECIO"),"1",total};
    temp.addRow(nuevo);
    
//tabla.setValueAt(r.getString("PRO_NOMBRE"), 0, 0);
//tabla.setValueAt(r.getString("PRO_CODIGO"), 0, 1);
//tabla.setValueAt(r.getString("PRO_PRECIO"), 0, 2);
}

tabla2.requestFocus();

tabla2.changeSelection(tabla2.getRowCount()-1, 0, false,false);




}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al extraer datos"+e.toString());
} 
        jTextField1.setText("");
     } 
     
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
busqueda = new Busqueda_productos();
       
       busqueda.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
    try {
            DefaultTableModel modelo=(DefaultTableModel) tabla2.getModel();
            
            
                modelo.removeRow(tabla2.getSelectedRow());
                tabla2.requestFocus();
tabla2.changeSelection(tabla2.getRowCount()-1, 0, false,false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_borrarActionPerformed

    private void Alt_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alt_botonActionPerformed
alter=new Alt();
   

        
Connection miConexion;
        miConexion=Conexion.GetConnection();
      
        if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
        
        try{
Statement st = miConexion.createStatement();
ResultSet r=st.executeQuery("SELECT * FROM equivalente,producto WHERE equivalente.PRO_CODIGO='"+busqueda.tabla.getValueAt(busqueda.tabla.getSelectedRow(), 1)+"'and producto.PRO_CODIGO=equivalente.EQUI_PRO ;");

while(r.next()) {

    DefaultTableModel temp = (DefaultTableModel) alter.tabla_alt.getModel();
    Object nuevo[]= {r.getString("EQUI_PRO"),r.getString("PRO_NOMBRE"),r.getString("PRO_PRECIO")};
    temp.addRow(nuevo);
    

}


}catch(Exception e){
JOptionPane.showMessageDialog(null, "Error al extraer datos"+e.toString());
}
        alter.show();
    
    }//GEN-LAST:event_Alt_botonActionPerformed

    private void n_atencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_atencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_atencionActionPerformed

    private void ven_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ven_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ven_codActionPerformed

    private void ven_codFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ven_codFocusLost
       ven_cod.setBackground(Color.WHITE);
        Connection miConexion;
        miConexion=Conexion.GetConnection();
      
        if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
        
        try{
Statement st = miConexion.createStatement();
ResultSet r=st.executeQuery("SELECT * FROM vendedor WHERE ven_cod="+Integer.parseInt(ven_cod.getText()));

while(r.next()) {

    ven_nom.setText(r.getString(3));
    

}


}catch(Exception e){
//JOptionPane.showMessageDialog(null, "Error al extraer datos"+e.toString());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_ven_codFocusLost

    private void ven_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ven_codKeyPressed
           if(evt.getExtendedKeyCode()==10){
        Connection miConexion;
        miConexion=Conexion.GetConnection();
      
        if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
        
        try{
Statement st = miConexion.createStatement();
ResultSet r=st.executeQuery("SELECT * FROM vendedor WHERE ven_cod="+Integer.parseInt(ven_cod.getText()));

   
   
    
while(r.next()) {
  
    ven_nom.setText(r.getString(3));
   

}


}catch(Exception e){
JOptionPane.showMessageDialog(null, "Ingrese codigo vendedor");
} 
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_ven_codKeyPressed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased


        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void tabla2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tabla2InputMethodTextChanged
      // TODO add your handling code here:
    }//GEN-LAST:event_tabla2InputMethodTextChanged

    private void tabla2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabla2PropertyChange
    
    }//GEN-LAST:event_tabla2PropertyChange

    private void tabla2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla2KeyPressed

          // TODO add your handling code here:
    }//GEN-LAST:event_tabla2KeyPressed

    private void tabla2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla2KeyTyped
  // TODO add your handling code here:
    }//GEN-LAST:event_tabla2KeyTyped

    private void tabla2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla2KeyReleased
     
        if(evt.getKeyCode()==KeyEvent.VK_MULTIPLY){
        int nuevac;
nuevac=Integer.parseInt(JOptionPane.showInputDialog("Nueva cantidad", tabla2.getValueAt(tabla2.getSelectedRow(), 3)));
tabla2.setValueAt(nuevac, tabla2.getSelectedRow(), 3);
int nuevot;
nuevot=nuevac*Integer.parseInt(tabla2.getValueAt(tabla2.getSelectedRow(), 2).toString());
tabla2.setValueAt(nuevot, tabla2.getSelectedRow(), 4);
}     // TODO add your handling code here:
    }//GEN-LAST:event_tabla2KeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      home=new Home(permiso);
      home.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void tabla2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabla2FocusGained
tabla2.setBackground(Color.pink);
        int total=0;
        for(int i= 0;i<tabla2.getRowCount();i++){
total=total+Integer.parseInt(String.valueOf(tabla2.getValueAt(i, 4)));
}
        total_tf.setText(String.valueOf(total));        // TODO add your handling code here:
    }//GEN-LAST:event_tabla2FocusGained

    private void desc_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desc_tfKeyPressed
int nuevototal=0; 
 int total=0;
        if (evt.getKeyCode()==10){
           
        for(int i= 0;i<tabla2.getRowCount();i++){
total=total+Integer.parseInt(String.valueOf(tabla2.getValueAt(i, 4)));
}
        if(desc_tf.getText().isEmpty()){nuevototal=total;
        desc_tf.setText("0");
        total_tf.setText(String.valueOf(nuevototal));
        }
    nuevototal=total-((total*Integer.parseInt(desc_tf.getText()))/100);
    total_tf.setText(String.valueOf(nuevototal));

}        // TODO add your handling code here:
    }//GEN-LAST:event_desc_tfKeyPressed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
jTextField1.setBackground(Color.PINK);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void ven_codFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ven_codFocusGained
     ven_cod.setBackground(Color.PINK);    // TODO add your handling code here:
    }//GEN-LAST:event_ven_codFocusGained

    private void desc_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_desc_tfFocusGained
desc_tf.setBackground(Color.PINK);         // TODO add your handling code here:
    }//GEN-LAST:event_desc_tfFocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
jTextField1.setBackground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    private void desc_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_desc_tfFocusLost
desc_tf.setBackground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_desc_tfFocusLost

    private void tabla2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabla2FocusLost
tabla2.setBackground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_tabla2FocusLost

    private void print_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_bActionPerformed
 String doc="default";
 if(jCheckBox1.isSelected()){doc=jCheckBox1.getText();}
 if(jCheckBox3.isSelected()){doc=jCheckBox3.getText();}
 if(jCheckBox4.isSelected()){doc=jCheckBox4.getText();}
 if(jCheckBox5.isSelected()){doc=jCheckBox5.getText();}
        Connection miConexion;
        miConexion=Conexion.GetConnection();
      
        if(miConexion!=null)
        {
           // JOptionPane.showMessageDialog(null, "Conexión Realizada Correctamente");
        }
        
        try{
String query = " insert into atencion (ate_corr, ate_total,ate_fpago, ven_cod)"
        + " values (?, ?, ?,?)";
 
      // create the mysql insert preparedstatement
      PreparedStatement preparedStmt = miConexion.prepareStatement(query);
    preparedStmt.setInt    (1, Integer.parseInt(n_atencion.getText()));
    preparedStmt.setInt    (2, Integer.parseInt(total_tf.getText()));
    preparedStmt.setString (3, doc);
    preparedStmt.setInt    (4, Integer.parseInt(ven_cod.getText()));
      
 
      // execute the preparedstatement
      preparedStmt.execute();


}catch(Exception e){
JOptionPane.showMessageDialog(null, "error: "+e);
}
        String text;
String total;
Imprimir print;
text=n_atencion.getText();
total=total_tf.getText();
 print =new Imprimir(text,total);
 print.imprimir();

// TODO add your handling code here:
    }//GEN-LAST:event_print_bActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p_venta(permiso).setVisible(true);
                 
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alt_boton;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField desc_tf;
    private javax.swing.ButtonGroup documentos_bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField n_atencion;
    private javax.swing.JButton print_b;
    public static javax.swing.JTable tabla2;
    private javax.swing.JTextField total_tf;
    private javax.swing.JTextField ven_cod;
    private javax.swing.JTextField ven_nom;
    // End of variables declaration//GEN-END:variables

 
    public void keyTyped(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
    public void keyPressed(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
